# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f9b57d6cc00751015e2958d4327dbee66132e3a291c5ccd5fdb5f37b9a0bdb97fd51406afe6ec96a76482fff3938469f00a66cdf928845724cb0aa4602627ae

test:
  secret_key_base: 7256fdf3f6ec6b8023338cfd3892a6d3d6e66e9720937894839dae8b21065f914d8c0feaed9f31339febe28f4df209c385ed8d9ca4790373cecd2431efa68e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
